import { Rat } from "lucide-react"
import "./globals.css"
import { Inter } from "next/font/google"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import InstanceSelector from "./[instance_url]/instance-selector"
import { fetchLemmyInstances } from "@/lib/lemmy"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

const NavBar = async () => {
    const instances = await fetchLemmyInstances()
    const data = instances.map(({ name, url }) => ({
        value: url,
        label: name,
    }))

    return (
        <header className="fixed p-4">
            <div className="flex items-center gap-4">
                <Button asChild variant="ghost">
                    <Link href="/">
                        <Rat className="h-6 w-6" />
                        <span className="sr-only">Home</span>
                    </Link>
                </Button>
                <InstanceSelector data={data} />
            </div>
        </header>
    )
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {children}
            </body>
        </html>
    )
}
